name: Release
on:
   push:
     tags:
       - 'v\d+'

jobs:
  create-issue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          tag: ${{ github.ref_name }}
          writeToFile: false

      - name: Create issue
        id: issue
        env:
          TAG_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        run: |
          TITLE="Release ${{ github.ref_name }}"
          BODY=$(cat << 'EOF'

          # Release ${{ github.ref_name }}

          Автор релиза: @${{ github.actor }}
          Дата релиза: ${{ github.event.head_commit.timestamp }}
          Версия релиза: ${{ github.ref_name }}

          ## CHANGELOG
          ${{ steps.changelog.outputs.changes }}

          EOF
          )

          ISSUE_ID=$(gh issue list --json number,title -q \
            ".[] | select(.title == \"$TITLE\") | .number")
          if [ ! -z "$ISSUE_ID" ]; then
            gh issue edit $ISSUE_ID --body "$BODY"
          else
            gh issue create --title "$TITLE" --body "$BODY" --assignee ${{ github.actor }} --label "release"
            ISSUE_ID=$(gh issue list --json number,title -q \
            ".[] | select(.title == \"$TITLE\") | .number")
          fi
          echo "issueId=$ISSUE_ID" >> "$GITHUB_OUTPUT"

    outputs:
      issueNumber: ${{ steps.issue.outputs.issueId }}

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: [create-issue]
    steps:
      - name: Run check-tests
        uses: ./.github/workflows/check-tests.yml

      - name: Comment issue with test results
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ needs.create-issue.outputs.issueNumber }}
          body: |
            Download test results:
            ${{github.server_url}}/${{ github.repository }}/actions/runs/${{github.run_id}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
  deploy:
    name: Run Deploy
    uses: ./.github/workflows/deploy.yml